spring:
  datasource:
    username: root
    password: Password123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myDb?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
server:
   port: 8082



